FROM ubuntu:21.04 AS base

USER root
RUN useradd tcms

ADD ./Makefile /home/tcms/Makefile
ADD ./Makefile.PL /home/tcms/Makefile.PL
RUN mkdir /home/tcms/.tcms
RUN mkdir -p /home/tcms/www/scripts
RUN chown -R tcms /home/tcms

WORKDIR /home/tcms

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y make
RUN make prereq-debian
