#!/bin/bash
[[ -e run/tcms.pid ]] && pkill -F run/tcms.pid
sudo www/server.psgi --listen run/tcms.sock --workers 20 --group www-data --user $USER --daemonize --pid run/tcms.pid
sudo chmod 0770 run/tcms.sock
echo "tCMS running as PID "`cat run/tcms.pid`
