#!/bin/bash
pkill -F run/tcms.pid
sudo WWW_VERBOSE=1 www/server.psgi --listen run/tcms.sock --group www-data --user $USER --daemonize --pid run/tcms.pid
#XXX Net::Server does not expect to run as a user other than that of the webserver
sudo chmod 0775 run/tcms.sock
