#!/bin/bash
[[ -e run/tcms.pid ]] && pkill -F run/tcms.pid
sudo www/server.psgi --listen run/tcms.sock --group www-data --user $USER --daemonize --pid run/tcms.pid
#XXX Net::Server does not expect to run as a user other than that of the webserver
sudo chmod 0770 run/tcms.sock
echo "tCMS running as PID "`cat run/tcms.pid`
