all:
	git init
	git remote add origin https://github.com/Troglodyne-Internet-Widgets/tCMS.git
	git fetch
	git checkout -f -b --track -b provisioner origin/provisioner
	echo "%TCMS_HOSTNAME%" > TCMS_HOSTNAME
	echo "%TCMS_USERNAME%" > TCMS_USERNAME
	make -f Installer.mk all
