<div id="lefttitle" class="toplel">
 <?php
  echo $config['htmltitle'];
 ?>
</div>
<div id="midtitle" class="toplel">
</div>
<button title="Menu" id="clickme">&#9776;</button>
<div id="righttitle" class="toplel">
 <a href="index.php?nav=2" title="Micro Blog" class="topbar">LinkLog</a>
 <a href="index.php?nav=3" title="Blog" class="topbar">Blog</a>
 <a href="index.php?nav=1&amp;dir=fileshare" title="File Share" class="topbar">Fileshare</a>
 <a href="index.php?nav=4" title="About" class="topbar">About</a>
</div>
