<p class="title">
 General settings:
</p>
<hr />
INSERT FORM HERE
<hr />

<p class="title">
 User management:
</p>
<hr />
INSERT USER TABLE W/USER DROPDOWN FORM HERE
<hr />

<p class="title">
 Theme cloner:
</p>
<hr />
<p>
  Want to write your own theme?
  Clone a theme here then see the <a href="https://tcms.troglodyne.net/index.php?nav=5&post=fileshare/manual/Chapter 03-Customization.post" title="GET UR MIND RITE">styling guide</a>
  for information on how tCMS' templates, image sets and CSS work in the theming system.
</p>
INSERT FORM HERE
