<p class="title">
 tCMS General Settings - Edit these Locally (for now).
</p>
<hr />
<p class="title">
 Configuration Variables
</p>
For now, every big config variable is set in /sys/admin/config/main.json. Refer to it if you know what you are doing.<br /><br />
Soon I will have a users.json defining what users are there (or alias http auth users).
<p class="title">
Themes: Coming soon.
</p>
<!--<form id="themeForm" method="post" name="themeForm">
<select name="selectedTheme">
  <?php
    

    //echo '<option></option>';
  ?>
 </select>
</form>-->
<p>
  Want to write your own theme (or modify one since I haven't finished the theme selector here)? Please see the <a href="teodesian.net/tCMS/index.php?nav=5&post=fileshare/manual/Chapter 03-Customization.post" title="GET UR MIND RITE">styling guide</a>.
</p>
