#!/bin/sh
WD=`dirname $(readlink -f $0)`
UPPER=`dirname $WD`
echo $WD
echo $UPPER
cd $WD
perlbrew init
perlbrew download stable
LATEST_TARBALL=$(ls -1 ~/perl5/perlbrew/dists/ | tail -n1)
rm -rf src
tar --one-top-level=src --strip-components=1 -zxf ~/perl5/perlbrew/dists/$LATEST_TARBALL
rm -rf ../perl5
mkdir ../perl5
cd src
./Configure -des -Dprefix=$UPPER/perl5
make -j8
make -j8 install
cd ../..
PERL_MM_USE_DEFAULT=1 perl5/bin/perl -MCPAN -e 'install "App::cpanminus"'
perl5/bin/cpanm --installdeps .
